import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generateLotReport = async (lot, farm, farmer, traceEvents, quality) => {
  const doc = new jsPDF();
  
  // Header with logo
  doc.setFontSize(20);
  doc.setTextColor(139, 69, 19);
  doc.text('Coffee Traceability Report', 14, 20);
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);
  doc.text(`Report ID: ${lot.lot_number}`, 14, 37);
  
  // Lot Information
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('1. Lot Information', 14, 50);
  
  doc.autoTable({
    startY: 55,
    head: [['Field', 'Value']],
    body: [
      ['Lot Number', lot.lot_number],
      ['Farm Name', farm?.name || 'N/A'],
      ['Farmer Name', farmer?.name || 'N/A'],
      ['Harvest Date', new Date(lot.harvest_date).toLocaleDateString()],
      ['Processing Method', lot.processing_method || 'N/A'],
      ['Quantity (kg)', lot.quantity_kg?.toLocaleString() || 'N/A'],
      ['SCA Score', quality?.total_score || 'Not assessed'],
      ['Grade', lot.grade || 'N/A'],
    ],
    theme: 'striped',
    headStyles: { fillColor: [139, 69, 19] },
    styles: { fontSize: 10 },
  });
  
  // Traceability Timeline
  let y = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.text('2. Traceability Timeline', 14, y);
  y += 5;
  
  if (traceEvents && traceEvents.length > 0) {
    const timelineData = traceEvents.map(event => [
      new Date(event.event_date).toLocaleDateString(),
      event.event_type.toUpperCase(),
      event.description || '-'
    ]);
    
    doc.autoTable({
      startY: y,
      head: [['Date', 'Event Type', 'Description']],
      body: timelineData,
      theme: 'striped',
      headStyles: { fillColor: [100, 100, 100] },
      styles: { fontSize: 9 },
    });
    y = doc.lastAutoTable.finalY + 10;
  } else {
    doc.setFontSize(10);
    doc.text('No trace events recorded', 14, y);
    y += 10;
  }
  
  // EUDR Compliance
  doc.setFontSize(14);
  doc.text('3. EUDR Compliance', 14, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(0, 100, 0);
  doc.text('✓ GPS Coordinates Recorded', 14, y);
  y += 7;
  doc.text('✓ Deforestation-Free Declaration', 14, y);
  y += 7;
  doc.text('✓ Due Diligence Statement', 14, y);
  y += 7;
  doc.text('✓ Traceability Verified', 14, y);
  y += 7;
  
  if (farm?.latitude && farm?.longitude) {
    doc.setTextColor(0, 0, 0);
    doc.text(`Farm Location: ${farm.latitude}, ${farm.longitude}`, 14, y);
    y += 7;
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('This report is generated by Coffee Traceability System', 14, 280);
  doc.text(`Verified: ${new Date().toISOString().split('T')[0]}`, 14, 287);
  
  // Save PDF
  doc.save(`EUDR_Report_${lot.lot_number}.pdf`);
};